name: serj
description: Easily convert your usual single/multiple select or dropdown into page, dialog, or bottom sheet with various choice input such as radio, checkbox, switch, chips, or custom widget.
homepage: https://github.com/akbarpulatov/flutter_smart_select
version: 6.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
    
  collection: ^1.16.0
  flutter_sound: ^9.2.13
#    path: ../ # Flutter Sound Dir
# ============================================================================
  shared_preferences: ^2.2.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2
  permission_handler: ^6.0.1
  path: ^1.6.4
  #flutter_ffmpeg: ^0.3.1
  intl: ^0.17.0
  audioplayers: ^5.2.0
  just_audio: ^0.9.11
  audio_session: ^0.1.6
  http: ^1.1.0
  prompt_dialog: ^1.0.13
  #settings_ui: ^2.0.2
  fluttertoast: ^8.2.2
  #settings_ui: 
  awesome_select: ^6.0.0
  dio: ^4.0.6
  sticky_headers: ^0.3.0+2
  dropdown_button2: ^2.3.9
  #easy_settings: ^1.0.0
  cached_network_image: ^3.0.0
dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  liquid_pull_to_refresh: ^3.0.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - res/icons/ic_play.png
  - res/icons/ic_play_disabled.png
  - res/icons/2.0x/ic_play.png
  - res/icons/3.0x/ic_play.png
  - res/icons/ic_stop.png
  - res/icons/ic_stop_disabled.png
  - res/icons/2.0x/ic_stop.png
  - res/icons/3.0x/ic_stop.png
  - res/icons/ic_pause.png
  - res/icons/ic_pause_disabled.png
  - res/icons/2.0x/ic_pause.png
  - res/icons/3.0x/ic_pause.png
  - res/icons/ic_mic.png
  - res/icons/ic_mic_disabled.png
  - res/icons/2.0x/ic_mic.png
  - res/icons/3.0x/ic_mic.png
  - res/icons/ic_volume_down.png
  - res/icons/2.0x/ic_volume_down.png
  - res/icons/3.0x/ic_volume_down.png
  - res/icons/ic_volume_up.png
  - res/icons/2.0x/ic_volume_up.png
  - res/icons/3.0x/ic_volume_up.png

  - assets/
  - assets/samples/
  - assets/noises/
  #- assets/extract/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
